name: Build and Deploy Code

on:
  push:
    branches: ["dev1"]
  pull_request:
    branches: ["dev1"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Say hi from machine
        run: echo "Hello Omar"
